#           __                       _
#   _ __   /__\ ___ _ __   ___  _ __| |_
#  | '_ \ / \/// _ \ '_ \ / _ \| '__| __|
#  | | | / _  \  __/ |_) | (_) | |  | |_
#  |_| |_\/ \_/\___| .__/ \___/|_|   \__|
#                  |_|
#       github.com/nickuc/nReport

# Define o tempo (em minutos) de cooldown do report.
delay: 5

# Define se reports com motivos customizados podem ser enviados.
allow-other-reason: true

# Define a lista de motivos.
reports:
  - "Exploração de falhas/Bugs"
  - "Uso de Hack"
  - "Uso de clientes alternativos"
  - "Ofensas/Ameaças"
  - "Spam/Flood"
  - "Nickname impróprio"