#           __                       _
#   _ __   /__\ ___ _ __   ___  _ __| |_
#  | '_ \ / \/// _ \ '_ \ / _ \| '__| __|
#  | | | / _  \  __/ |_) | (_) | |  | |_
#  |_| |_\/ \_/\___| .__/ \___/|_|   \__|
#                  |_|

# Configuração do nReport
# Precisa de suporte? Entre em nosso grupo do discord: https://www.nickuc.com/discord

# Modo de depuração: É utilizado para correção de problemas no plugin.
debug-mode: false

Config:
  # Quantidade de tempo em minutos para se realizar um report.
  reportsDelay: 5

  # Permitir reports diferentes do configurado?
  allow-other-reports: true

  # Lista de reports disponíveis
  reports:
    - "Exploração de falhas/Bugs"
    - "Uso de Hack"
    - "Uso de clientes alternativos"
    - "Ofensas/Ameaças"
    - "Spam/Flood"
    - "Nickname impróprio"
